<a href="https://colab.research.google.com/github/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/%C3%81lgebra_lineal_con_Python_Vectores%2C_operaciones_con_vectores%2C_rectas_y_planos_en_el_espacio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="logo.fua" height="100px" src="https://www.uamerica.edu.co/wp-content/images/escudo.png" align="left" hspace="10px" vspace="0px"></p>

<p><img alt="logo.fua" height="26px" src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nd.svg" align="right" hspace="0px" vspace="11px"></p>


# <center> <font size="6">**ÁLGEBRA LINEAL CON PYTHON** <center>*Jhonny Osorio Gallego &nbsp; &nbsp; &nbsp;<p>*</font> 

#**VECTORES, OPERACIONES CON VECTORES, RECTAS Y PLANOS EN EL ESPACIO**



##**LIBRERÍA SIMBÓLICA SYMPY**
**SymPy** es una biblioteca de Python para matemáticas simbólicas. Su objetivo es convertirse en un sistema de álgebra computacional (CAS) con todas las funciones, manteniendo el código lo más simple posible para que sea comprensible y fácilmente extensible. SymPy está escrito completamente en Python.[sympy.org](https://www.sympy.org/en/index.html)

In [2]:
from sympy import *
from sympy.physics.vector import *
e = ReferenceFrame('e')
init_printing()
x,y,z,A,B,C = symbols("x y z A B C ")


#**DEFINICIÓN DE VECTOR**
Un vector con dimensión $n$, es una $n$-tupla de números reales que pertenece a $\mathbb {R} ^{n}$ en donde cada elemento de la  $n$-tupla recibe el nómbre de componente.

De esta manera un vector $\vec{V} \in \mathbb {R} ^{n}$ se nota cómo:

$$\vec{V} = (x_1,x_2,\cdots,x_n) = x_1\hat{e_1} + x_2\hat{e_2} +\cdots+ x_n\hat{e_n}$$

Donde  $\hat{e_i}$ son los respectivos vectores unitarios para cada una de las componentes y donde $\hat{e_1}= \hat{\imath} $,  $\hat{e_2}= \hat{\jmath}$, $\hat{e_3}= \hat{k} $
 

Cuando los vectores pertenecen a $\mathbb {R} ^{n}$ con $n=1,2 \hspace{0.2cm} \text{o} \hspace{0.2cm} 3$  podemos realizar **representaciones geométricas** de los mismos en la recta, el plano y el espacio respectivamente.

#**DEFINICIÓN DE VECTOR EN SYMPY** 

#**Vectores unidimensionales**
Son vectores $\vec{V} \in \mathbb {R}$ y poseen una sola componente, se notan como: 

$$\vec{V} =  \langle x \rangle \hspace{0.2cm} \text{donde}    \hspace{0.2cm} x \in \mathbb {R}$$




###**Ejemplo:** 
Define el vector  $\vec{V} = \langle 2 \rangle = 2 \hat{\imath} $ en SymPy cuya gráfica se presenta a continuación:


<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/vector1.png?raw=true"  height="200" />



### **Forma 1** (como una matriz columna)

In [38]:
V = Matrix([2])
V

[2]

### **Forma 2** (en términos de vectores unitarios)

In [39]:
V = 2*e.x 
V

#**Vectores bidimensionales**
Son vectores $\vec{V} \in \mathbb {R^2}$ y poseen dos componentes, se notan como: 

$$\vec{V} =  \langle x,y \rangle \hspace{0.2cm} \text{donde}    \hspace{0.2cm} x,y \in \mathbb {R}$$

###**Ejemplo:** 
Define el vector  $\vec{V} = \langle -2,3 \rangle = -2 \hat{\imath} + 3 \hat{\jmath} $ en SymPy cuya gráfica se presenta a continuación:

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/vector2d.png?raw=true"  height="350" />

### **Forma 1** (como una matriz columna)

In [ ]:
A = Matrix([-2,3])
A

⎡-2⎤
⎢  ⎥
⎣3 ⎦

### **Forma 2** (en términos de vectores unitarios)

In [ ]:
V = -2*e.x +3*e.y
V

#**Vectores tridimensionales**
Son vectores $\vec{V} \in \mathbb {R^3}$ y poseen tres componentes, se notan como: 

$$\vec{V} =  \langle x,y,z \rangle \hspace{0.2cm} \text{donde}    \hspace{0.2cm} x,y,z \in \mathbb {R}$$

###**Ejemplo:** 
Define el vector  $\vec{V} = \langle 1,2,3 \rangle = 1 \hat{\imath} + 2 \hat{\jmath} +3\hat{k} $ en SymPy cuya gráfica se presenta a continuación:


<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/vector3d.PNG?raw=true"  height="250" />







### **Forma 1** (como una matriz columna)

In [ ]:
V = Matrix([1,2,3])
V

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

### **Forma 2** (en términos de vectores unitarios)

In [ ]:
V = 1*e.x +2*e.y +3*e.z
V

#**Vectores $n$ dimensionales**
Son vectores $\vec{V} \in \mathbb {R^n}$ con $n > 3$, se notan como: 

$$\vec{V} =  \langle x_1,x_2,\cdots ,x_n \rangle \hspace{0.2cm} \text{donde}    \hspace{0.2cm} x_i \in \mathbb {R}$$

###**Ejemplo:** 
Define el vector  $\vec{V} = \langle 1,2,3,4,5 \rangle $ en SymPy.

### **Forma 1** (como una matriz columna)

In [ ]:
V = Matrix([1,2,3,4,5])
V

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎢3⎥
⎢ ⎥
⎢4⎥
⎢ ⎥
⎣5⎦

#**Traslación de un vector al origen en el plano**

Sea $\vec{V}$ el vector del plano que tiene como punto inicial $A = (x_A,y_A)$ y como punto final $B = (x_B,y_B) $ entonces podemos afirmar:

$$\vec{V} = (x_B-x_A,,y_B- y_A)$$
 
### **Ejemplo:**
Si $P = (4,2)$ y $Q = (7,6)$ halla las coordenadas del vector $\vec{V}=\vec{PQ}$


<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/trasla1.png?raw=true"  height="300" />


In [ ]:
P = (4,2)
Q = (7,6)

V = Matrix([Q[0]-P[0],Q[1]-P[1]])
V

⎡3⎤
⎢ ⎥
⎣4⎦

#**Traslación de un vector al origen en el espacio**

Sea $\vec{V}$ el vector del plano que tiene como punto inicial $A = (x_A,y_A,z_A)$ y como punto final $B = (x_B,y_B,z_B) $ entonces podemos afirmar:

$$\vec{V} = (x_B-x_A,,y_B- y_A,z_B- z_A)$$
 
### **Ejemplo:**

Si $P = (2,3,2)$ y $Q = (3,5,5)$ halla las coordenadas del vector $\vec{V}=\vec{PQ}$

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/trasla2.PNG?raw=true"  height="300" />


In [43]:
P = (2,3,2)
Q = (3,5,5)

V = Matrix([Q[0]-P[0],Q[1]-P[1],Q[2]-P[2]])
V

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

#**CARACTERISTICAS DE UN VECTOR GEOMÉTRICO**

# **Magnitud de un vector**

Sea  $\vec{V} \in \mathbb {R^n}$ de la forma $\vec{V} = (x_1,x_2 \cdots,x_n)$ el **módulo**, la **norma** o **magnitud** del vector se define y se nota como:

$$||V||= \sqrt{x_1^2+x_2^2+\cdots+x_{n-1}^2+x_{n}^2}$$

Cuando $n\leq 3$ la **norma** conincide con la longitud del vector en su **representación gráfica**.

##**Ejemplo 1:**

Halla la **norma** del vector representado en la figura:

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/magnitud1.png?raw=true"  height="150" />





###**Forma 1**

In [36]:
V = Matrix([2])
V.norm()

###**Forma 2**

In [37]:
V = 2*e.x 
V.magnitude()

##**Ejemplo 2:**

Halla la **norma** del vector representado en la figura:

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/magnitud2d.png?raw=true"  height="300" />

###**Forma 1**

In [43]:
V = Matrix([-2,3])
V.norm()

###**Forma 2**

In [44]:
V = -2*e.x+3*e.y 
V.magnitude()

##**Ejemplo 3:**

Halla la **norma** del vector representado en la figura:

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/magnitud3d.PNG?raw=true"  height="300" />

###**Forma 1**

In [45]:
V = Matrix([1,2,3])
V.norm()

###**Forma 2**

In [46]:
V = 1*e.x+2*e.y+3*e.z
V.magnitude()

##**Ejemplo 4:**

Halla la **norma** del vector 

$$\vec{V} = \langle 2,4,5,6 \rangle $$

###**Forma 1**

In [47]:
V = Matrix([2,4,5,6])
V.norm()

###**Forma 2**

In [48]:
V = Matrix([2,4,5,6])
sqrt(V[0]**2 + V[1]**2 + V[2]**2 + V[3]**2)

#**Dirección de un vector en el plano**

#**Dirección de un vector en el espacio**

#**TIPOS DE VECTORES**

#**Vector fila**
Un **vector fila** o **vector renglón** es una matriz formada por una fila y $n$ entradas y por lo tanto de tamaño $1 \times n$, de la forma:

$$\vec{V} = (x_1,x_2 \cdots,x_n)$$

###**Ejemplo 1:**

In [ ]:
V = Matrix(1,3,[4,5,6])
V

[4  5  6]

###**Ejemplo 2:** (vector fila aleatorio)

In [ ]:
V = randMatrix(1,4,min=-5, max=5)
V

[-1  4  -2  -2]

#**Vector columna**
Un **vector columna** es una matriz formada por una columna y $n$ entradas y por lo tanto de  tamaño $n \times 1$, de la forma:

$$\vec{V} = \begin{pmatrix}x_1 \\ x_2 \\ \vdots \\ x_n\end{pmatrix} $$

###**Ejemplo 1:**

In [ ]:
V = Matrix([2,5,7])
V

⎡2⎤
⎢ ⎥
⎢5⎥
⎢ ⎥
⎣7⎦

###**Ejemplo 2:** (vector columna aleatorio)

In [ ]:
V = randMatrix(4,1,min=-5, max=5)
V

⎡5⎤
⎢ ⎥
⎢4⎥
⎢ ⎥
⎢5⎥
⎢ ⎥
⎣2⎦

#**Vector nulo**
un **vector nulo** o **vector cero** es un vector que posee módulo o mágnitud nula, se representa de la forma 

$$\vec{0} = \begin{pmatrix}0 \\ 0 \\ \vdots \\ 0\end{pmatrix} \hspace{0.5cm} \text{o} \hspace{0.5cm} \vec{0} = (0,0 \cdots,0)$$

respectivamente como **vector columna** o **vector fila**.

###**Ejemplo 1:**

In [ ]:
O = zeros(1,4)
O

[0  0  0  0]

###**Ejemplo 2:**

In [ ]:
O = zeros(3,1)
O

⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦

#**Vector unitario o versor**