<a href="https://colab.research.google.com/github/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/%C3%81lgebra_lineal_con_Python_Vectores_y_operaciones_con_vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="logo.fua" height="100px" src="https://www.uamerica.edu.co/wp-content/images/escudo.png" align="left" hspace="10px" vspace="0px"></p>

<p><img alt="logo.fua" height="26px" src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nd.svg" align="right" hspace="0px" vspace="11px"></p>


# <center> <font size="6">**ÁLGEBRA LINEAL CON PYTHON** <center>*Jhonny Osorio Gallego* &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<p></font> 

# **VECTORES Y OPERACIONES CON VECTORES**



## **LIBRERÍA SIMBÓLICA SYMPY**
**SymPy** es una biblioteca de Python para matemáticas simbólicas. Su objetivo es convertirse en un sistema de álgebra computacional (CAS) con todas las funciones, manteniendo el código lo más simple posible para que sea comprensible y fácilmente extensible. SymPy está escrito completamente en Python.[sympy.org](https://www.sympy.org/en/index.html)

In [21]:
from sympy import *
from sympy.physics.vector import *

e = ReferenceFrame('e')
i = e.x 
j = e.y 
k = e.z

init_printing()
x,y,z,A,B,C = symbols("x y z A B C ")

## **MÓDULO EXTERNO PARA LA GRAFICACIÓN DE VECTORES**

El siguiente módulo permite la representación gráfica de vectores en el plano y el espacio y hace uso de la librería  de graficación **Plotly** y de arreglos multidimensionales **NumPy**, se crea como herramienta para una mejor comprensión de los conceptos vectoriales desde las actividades con el lenguaje de programación Python y se nombra como **plotvector**.

##**Clonamos el repositorio de álgebra lineal desde GitHub**

In [2]:
!git clone https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON

Cloning into 'ALGEBRA-LINEAL-CON-PYTHON'...
remote: Enumerating objects: 493, done.
remote: Counting objects: 100% (267/267), done.
remote: Compressing objects: 100% (267/267), done.
remote: Total 493 (delta 149), reused 0 (delta 0), pack-reused 226
Receiving objects: 100% (493/493), 1.90 MiB | 18.31 MiB/s, done.
Resolving deltas: 100% (264/264), done.


##**Accedemos al directorio**

In [3]:
import sys
sys.path.append('/content/ALGEBRA-LINEAL-CON-PYTHON')

##**Importamos módulo de graficación plotvector**

Importamos todas las funciones contenidas en el módulo de graficación llamado *plotvector*.

In [ ]:
from plotvector import *

# **MAGNITUD FÍSICA**

Son aquellas propiedades que poseen lo cuerpos f́ísicos y fenomenos que son susceptibles a ser medidas.

**Ejemplos:**  *la longitud, la masa, el tiempo, la velocidad, la fuerza y la temperatura*.

## **Magnitudes físicas escalares**

Son aquellas que para su definición necesitan de un número real y una unidad de  medida.

**Ejemplos:**  *la longitud, la masa, el tiempo y la temperatura*.


## **Magnitudes físicas  vectoriales**

Son aquellas que para su definición no solamente necesitan de un número real y una unidad de  medida, tambien se necesita especificar su dirección y sentido, para describirlas se usan los **vectores**.

**Ejemplos:**  *el desplazamiento, la velocidad, la cantidad de movimiento y la fuerza*.

# **DEFINICIÓN GEOMÉTRICA DE VECTOR**

Se define como un segmento de recta dirigido,  entre sus caracteristicas podemos apreciar: *punto inicial, magnitud, dirección y sentido*.



*   **Magnitud :** se define como la longitud del vector.
*   **Dirección:** es la recta soporte, recta directriz o linea de acción que contiene al vector.
*   **Sentido:** es la la punta de la flecha.

El ángulo $\theta$ que se mide respecto a una recta en particular determina  la dirreción y el sentido del vector.







<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/vector%20geom%C3%A9trico%20final.png?raw=true"  height="300" />



# **VECTORES IGUALES O EQUIVALENTES**

La relación que permite determinar si dos vectores son equivalentes se llama **relación de equipolencia**, dos vectores o mas son equipolentes si tienen la misma *magnitud, dirección y sentido*.

Decimos que dos vectores tienen la misma dirección si sus rectas directrices son paralelas.


<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/igualdad%20vectores.png?raw=true"  height="300" /> </center>

¿ Cuales de los siguientes vectores tienen la misma dirección, cuales tienen el mismo sentido, cuales tienen la misma magnitud y cuales son equipolentes?


# **Equipolencia de vectores desde la física**

Dos o más vectores son equipolentes cuando las magnitudes físicas que estos vectores describen tienen el mismo valor, las mismas unidades y producen los mismos efectos.

# **Equipolencia de vectores desde la  representación geometrica-sintética**

Decimos que dos vectores $\overrightarrow{AB}$ y $\overrightarrow{CD}$ son iguales o equipolentes, si al construir los segmentos $\overline{AC}$ y $\overline{CD}$ el cuadrilátero $ABCD$ es un paralelogramo.

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/Equipolencia%20sint%C3%A9tica.png?raw=true"  height="200" /> </center>


# **Equipolencia de vectores desde la  representación geométrica-cartesiana**

Decimos que dos vectores en el plano $\overrightarrow{AB}$ y $\overrightarrow{CD}$ donde $A = (A_x,A_y)$, $B = (B_x,B_y)$, $C= (C_x,C_y)$ y  $D= (D_x,D_y)$ son iguales, si se cumple:


<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/equipolencia-cartesiana.png?raw=true"  height="300" /> </center>





#**Definición de un vector en la librería SymPy**

En la libreria **SymPy** de python  un vector se define como una matriz columna, existen otras librerías como NumPy en donde se define como un arreglo, puede consultar en la documentación oficial [https://numpy.org/](https://numpy.org/).

In [ ]:
A = Matrix([1,2])
A

⎡1⎤
⎢ ⎥
⎣2⎦

In [ ]:
A = Matrix([1,2,3])
A

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

#**TRASLACIÓN DE UN VECTORES AL ORIGEN**

# **Traslación en el plano**

Sea $\vec{V}$ el vector del plano que tiene como punto inicial $A = (A_x,A_y)$ y como punto final $B = (B_x,B_y) $ entonces podemos afirmar:

$$\vec{V} = (B_x-A_x,B_y- A_y)$$


<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/vector%20fijo%20-plano.png?raw=true"  height="300" /></center>
 
### **Ejemplo:**
Si $P = (4,2)$ y $Q = (7,6)$ halla las coordenadas del vector $\vec{V}=\vec{PQ}$


<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/trasla1.png?raw=true"  height="300" />


In [ ]:
P = (4,2)
Q = (7,6)

V = Matrix([Q[0]-P[0],Q[1]-P[1]])
V

⎡3⎤
⎢ ⎥
⎣4⎦

## **Representación gráfica de la traslación en el plano** 

In [ ]:
plotvectors2D([(4,2),(7,6)],(3,4))

#**Traslación en el espacio**

Sea $\vec{V}$ el vector del plano que tiene como punto inicial $A = (A_x,A_y,A_z)$ y como punto final $B = (B_x,B_y,B_z) $ entonces podemos afirmar:

$$\vec{V} = (B_x-A_x,B_y-A_y,B_z- A_z)$$

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/vector%20fijo%20-espacio.png?raw=true"  height="300" /></center>
 
### **Ejemplo:**

Si $P = (2,3,2)$ y $Q = (3,5,5)$ halla las coordenadas del vector $\vec{V}=\vec{PQ}$

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/trasla2.PNG?raw=true"  height="300" />


In [ ]:
P = (2,3,2)
Q = (3,5,5)

V = Matrix([Q[0]-P[0],Q[1]-P[1],Q[2]-P[2]])
V

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

## **Representación gráfica de la traslación en el espacio** 

In [ ]:
plotvectors3D([(2,3,2),(3,5,5)],[1,2,3])

# **DEFINICIÓN ANALÍTICA DE VECTOR**
Un vector con dimensión $n$, es una $n$-tupla de números reales que pertenece a $\mathbb {R} ^{n}$ en donde cada elemento de la  $n$-tupla recibe el nómbre de componente.

De esta manera un vector $\vec{V} \in \mathbb {R} ^{n}$ se nota cómo:

$$\vec{V} = (x_1,x_2,\cdots,x_n) = x_1\hat{e_1} + x_2\hat{e_2} +\cdots+ x_n\hat{e_n}$$

Donde  $\hat{e_i}$ son los respectivos vectores unitarios para cada una de las componentes y donde $\hat{e_1}= \hat{\imath} $,  $\hat{e_2}= \hat{\jmath}$, $\hat{e_3}= \hat{k} $
 

Cuando los vectores pertenecen a $\mathbb {R} ^{n}$ con $n=1,2 \hspace{0.2cm} \text{o} \hspace{0.2cm} 3$  podemos realizar **representaciones geométricas** de los mismos en la recta, el plano y el espacio respectivamente.

#**DEFINICIÓN DE VECTORES USANDO LIBERÍA SYMPY** 

#**Vectores unidimensionales**
Son vectores $\vec{V} \in \mathbb {R}$ y poseen una sola componente, se notan como: 

$$\vec{V} =  ( x ) \hspace{0.2cm} \text{donde}    \hspace{0.2cm} x \in \mathbb {R}$$




###**Ejemplo:** 
Define el vector  $\vec{V} = ( 2 ) = 2 \hat{\imath} $ en SymPy cuya gráfica se presenta a continuación y realiza su gráfica con la función **plotvector2D** del módulo de graficación.

### **Forma 1** (como una matriz columna)

In [ ]:
V = Matrix([2])
V

[2]

### **Forma 2** (en términos de vectores unitarios)

In [12]:
V = 2*i
V

## **Representación gráfica en el eje de las absisas** 

In [ ]:
plotvectors2D([2,0])

#**Vectores bidimensionales**
Son vectores $\vec{V} \in \mathbb {R^2}$ y poseen dos componentes, se notan como: 

$$\vec{V} =  ( x,y )\hspace{0.2cm} \text{donde}    \hspace{0.2cm} x,y \in \mathbb {R}$$

###**Ejemplo:** 
Define el vector  $\vec{V} = (-2,3) = -2 \hat{\imath} + 3 \hat{\jmath} $ en SymPy cuya gráfica se presenta a continuación y realiza su gráfica con la función **plotvector2D** del módulo de graficación.


### **Forma 1** (como una matriz columna)

In [ ]:
A = Matrix([-2,3])
A

⎡-2⎤
⎢  ⎥
⎣3 ⎦

### **Forma 2** (en términos de vectores unitarios)

In [13]:
V = -2*i +3*j
V

## **Representación gráfica en el plano** 

In [ ]:
plotvectors2D([-2,3])

#**Vectores tridimensionales**
Son vectores $\vec{V} \in \mathbb {R^3}$ y poseen tres componentes, se notan como: 

$$\vec{V} = ( x,y,z ) \hspace{0.2cm} \text{donde}    \hspace{0.2cm} x,y,z \in \mathbb {R}$$

###**Ejemplo:** 
Define el vector  $\vec{V} = ( 1,2,3 ) = 1 \hat{\imath} + 2 \hat{\jmath} +3\hat{k} $ en SymPy y realiza su gráfica con la función **plotvectorf3D** del módulo de graficación.

### **Forma 1** (como una matriz columna)

In [ ]:
V = Matrix([1,2,3])
V

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

### **Forma 2** (en términos de vectores unitarios)

In [14]:
V = 1*i +2*j +3*k
V

## **Representación gráfica en el espacio** 

In [ ]:
plotvectors3D([1,2,3])

#**Vectores $n$ dimensionales**
Son vectores $\vec{V} \in \mathbb {R^n}$ con $n > 3$, se notan como: 

$$\vec{V} =  ( x_1,x_2,\cdots ,x_n ) \hspace{0.2cm} \text{donde}    \hspace{0.2cm} x_i \in \mathbb {R}$$

###**Ejemplo:** 
Define el vector  $\vec{V} = ( 1,2,3,4,5) $ en SymPy.

### **Forma 1:** (como una matriz columna)

In [ ]:
V = Matrix([1,2,3,4,5])
V

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎢3⎥
⎢ ⎥
⎢4⎥
⎢ ⎥
⎣5⎦

# **Magnitud, norma o módulo de un vector**

Sea  $\vec{V} \in \mathbb {R^{n}}$ de la forma $\vec{V} = (x_1,x_2 \cdots,x_n)$ el **módulo**, la **norma** o **magnitud** del vector se define y se nota como:

$$||V||= \sqrt{x_1^2+x_2^2+\cdots+x_{n-1}^2+x_{n}^2}$$

Cuando $n\leq 3$ la **norma** conincide con la longitud del vector en su **representación gráfica**.

##**Ejemplo 1:**

Halla la **norma** del vector representado en la figura:

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/magnitud1.png?raw=true"  height="150" />





###**Forma 1**

In [ ]:
V = Matrix([2])
V.norm()

###**Forma 2**

In [15]:
V = 2*i
V.magnitude()

##**Ejemplo 2:**

Halla la **norma** del vector representado en la figura:

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/magnitud2d.png?raw=true"  height="300" />

###**Forma 1**

In [ ]:
V = Matrix([-2,3])
V.norm()

###**Forma 2**

In [16]:
V = -2*i+3*j
V.magnitude()

##**Ejemplo 3:**

Halla la **norma** del vector representado en la figura:

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/magnitud3d.PNG?raw=true"  height="300" />

###**Forma 1**

In [ ]:
V = Matrix([1,2,3])
V.norm()

###**Forma 2**

In [17]:
V = 1*i+2*j+3*k
V.magnitude()

##**Ejemplo 4:**

Halla la **norma** del vector 

$$\vec{V} = ( 2,4,5,6) $$

###**Forma 1**

In [ ]:
V = Matrix([2,4,5,6])
V.norm()

###**Forma 2**

In [ ]:
V = Matrix([2,4,5,6])
sqrt(V[0]**2 + V[1]**2 + V[2]**2 + V[3]**2)

#**DIRECCIÓN Y SENTIDO DE UN VECTOR**

La dirección está definida por la recta soporte o linea de acción que contiene al vector y el sentido está determinado por la posición de la flecha en dicha recta, estas dos características determinan el ángulo.

#**Ángulo de un vector unidimensional** 

<center><img src="https://github.com/josorio398/ALGEBRA-LINEAL-CON-PYTHON/blob/master/im%C3%A1genes%20repositorio/vector%20unidimensional.PNG?raw=true"  height="300" />

In [18]:
A = Matrix([-2])

if A[0]> 0:
    angulo = 0
if A[0]<0 :
    angulo = 180
angulo


#**Ángulo de un vector bidimensional**





#**Ángulos de un vector tridimensional**

#**TIPOS DE VECTORES**

#**Vector fila**
Un **vector fila** o **vector renglón** es una matriz formada por una fila y $n$ entradas y por lo tanto de tamaño $1 \times n$, de la forma:

$$\vec{V} = (x_1,x_2 \cdots,x_n)$$

###**Ejemplo 1:**

In [ ]:
V = Matrix(1,3,[4,5,6])
V

[4  5  6]

###**Ejemplo 2:** (vector fila aleatorio)

In [ ]:
V = randMatrix(1,4,min=-5, max=5)
V

[-1  4  -2  -2]

#**Vector columna**
Un **vector columna** es una matriz formada por una columna y $n$ entradas y por lo tanto de  tamaño $n \times 1$, de la forma:

$$\vec{V} = \begin{pmatrix}x_1 \\ x_2 \\ \vdots \\ x_n\end{pmatrix} $$

###**Ejemplo 1:**

In [ ]:
V = Matrix([2,5,7])
V

⎡2⎤
⎢ ⎥
⎢5⎥
⎢ ⎥
⎣7⎦

###**Ejemplo 2:** (vector columna aleatorio)

In [ ]:
V = randMatrix(4,1,min=-5, max=5)
V

⎡2 ⎤
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎢-3⎥
⎢  ⎥
⎣3 ⎦

#**Vector nulo**
un **vector nulo** o **vector cero** es un vector que posee módulo o mágnitud nula, se representa de la forma 

$$\vec{0} = \begin{pmatrix}0 \\ 0 \\ \vdots \\ 0\end{pmatrix} \hspace{0.5cm} \text{o} \hspace{0.5cm} \vec{0} = (0,0 \cdots,0)$$

respectivamente como **vector columna** o **vector fila**.

###**Ejemplo 1:**

In [ ]:
O = zeros(1,4)
O

[0  0  0  0]

###**Ejemplo 2:**

In [ ]:
O = zeros(3,1)
O

⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦

#**VECTORES FORMA POLAR**

#**FUNCIONES Y MÉTODOS SOBRE VECTORES**

#**Dimensión de un vector**

In [ ]:
V = Matrix([1,2,3,4,5])
len(V)

#**Indexar una coordenada del vector**

In [ ]:
V = Matrix([1,2,3,4,5])
V[2]